### ISSUE TITLE
[Bug] AttributeError

### ISSUE THREAD

**Issue by Migan178** [gunyu1019/discord-extension-cog#1]
- error
```py
Traceback (most recent call last):
  File "C:\Users\tiger\project\kubot-python_version\index.py", line 4, in <module>
    client = interaction.Client(global_sync_command=True)
  File "C:\Users\tiger\project\kubot-python_version\.venv\lib\site-packages\discord\ext\interaction\client.py", line 90, in __init__
    self.add_listener(self._sync_command_task, "on_ready")
AttributeError: 'Client' object has no attribute 'add_listener'. Did you mean: '_listeners'?
```

-  os: windows 10 pro 19044.1469
- python version: 3.10.2 (venv)
- code
```py
from discord.ext import interaction
import json

client = interaction.Client(global_sync_command=True)

with open("config.json") as f:
    config = json.load(f)

@interaction.command(description="This is ping", name='ping')
async def ping(ctx: interaction.ApplicationContext):
    await ctx.send("pong!")
    return

client.add_interaction(ping)
client.run(config['token'])
```

- pycord 2.0.0a

**Comment by Migan178** [comment]
+ editor is vscode

**Comment by gunyu1019** [comment]
`client-independence`을 통해 독립적인 클라이언트를 통해 해결될 예정입니다.

**Comment by gunyu1019** [comment]
Fixed at #6
