### ISSUE TITLE
[Bug] Can't sync with discord bot when using SubCommand in InteractionCog

### ISSUE THREAD

**Issue by gunyu1019** [gunyu1019/discord-extension-cog#4]
## Summary<br/>
`interactionCog`를 통해 명령어에 `subcommand`를 등록했을 때, 디스코드에 등록된 애플리케이션 커맨드와 동기화하는 과정에서 예외가 발생합니다.

## To Reproduce<br/>

```py
...
client = interaction.Client(global_sync_command=True, intent=discord.Intent.default())

class ForSubCommandTest:
    def __init__(self, bot: interaction.Client):
        self.bot = bot

    @interaction.command()
    async def subcommand(self):
        return

    @subcommand.subcommand(name="param1")
    @interaction.option(name="option", description="This is argument for subcommand test")
    async def parameter1(self, ctx: interaction.ApplicationContext, argument: str):
        return

    @subcommand.subcommand(name="param2")
    async def parameter2(self, ctx: interaction.ApplicationContext, argument: str):
        return

client.add_interaction_cog(ForSubCommandTest(client))
...
```

## Expected Results<br/>
`interaction.Client`를 동기화(sync_command)하는 과정에서 `ApplicationContext` 변수를 `CommandOption`으로 인식하게 되어, `TypeError` 가 발생합니다.

## Actual Results<br/>
interactionCog를 활용하여 subcommand를 등록할 때, 예외가 발생하면 안되며 디스코드 애플리케이션 커맨드와 동기화되야 합니다.

## Exception<br/>
```pytb
Ignoring exception in on_ready
Traceback (most recent call last):
  File "...\venv\lib\site-packages\discord\client.py", line 393, in _run_event
    await coro(*args, **kwargs)
  File "...\discord\ext\interaction\client.py", line 282, in _sync_command_task
    await self._sync_command(command=command)
  File "...\discord\ext\interaction\client.py", line 203, in _sync_command
    await self.edit_command(command=command)
  File "...\discord\ext\interaction\client.py", line 129, in edit_command
    payload=command.to_register_dict()
  File "...\discord\ext\interaction\commands.py", line 451, in to_register_dict
    data['options'] = [opt.to_dict() for opt in self.options]
  File "...\discord\ext\interaction\commands.py", line 451, in <listcomp>
    data['options'] = [opt.to_dict() for opt in self.options]
  File "...\discord\ext\interaction\commands.py", line 298, in to_dict
    "options": [opt.to_dict() for opt in self.options]
  File "...\discord\ext\interaction\commands.py", line 298, in <listcomp>
    "options": [opt.to_dict() for opt in self.options]
  File "...\discord\ext\interaction\commands.py", line 194, in to_dict
    "type": self._get_type_id,
  File "...\discord\ext\interaction\commands.py", line 188, in _get_type_id
    raise TypeError("option type invalid (Subcommand and Subcommand Group, please use decorator)")
TypeError: option type invalid (Subcommand and Subcommand Group, please use decorator)
```

## System Information:<br/>
* Python Version: Python 3.8.6 (Virtual Environment)
* Package Version: ~ v0.5.1 (All versions before client-independence branch)

## Additional context<br/>

**Comment by gunyu1019** [comment]
Fixed at #6
